### PR TITLE
Add support for BumpyCase

### PR DESCRIPTION
**Pull request by dboskovic**
Hey @milanlandaverde. Awesome package. Just adding support for another use case.

### CODE REVIEW

**Comment by milanlandaverde** [comment]
Merged!

**Comment by dboskovic** [comment]
Could you do an npm version bump when you get a chance so I can reference it rather than my personal repo?

**Comment by milanlandaverde** [comment]
Just pushed latest at 1.2.1

**Comment by dboskovic** [comment]
Thanks!

**Pull request merged**
